config/routes.rb
Rails.application.routes.draw do
  root "admin/students#index"
  namespace :admin do
    resources :semester_klasses do
      collection do
        get :statement
        get :copy
        post :copy_create
      end
      resources :klass_students do
        # member do
        #   put :out, to: "klass_students#out"
        # end
      end
      resources :courses do
        member do
          post :insert_students
          put :start, to: "courses#start"
        end
        resources :attendances do
          member do
            put :mark
          end
        end
      end
    end
    resources :teachers
    resources :students
    resources :users
    resources :schools do
      resources :semesters do
        member do
          get :switch_thread_semester
        end
      end
      resources :campuses do
        member do
          get :switch_thread_campuse
        end
      end
      resources :semesters
    end
  end
  resource :session
  resources :passwords, param: :token
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/views/admin/shared/_alert.html.erb
<% if alert = flash[:alert] %>
  <div role="alert" class="alert alert-error alert-soft">
    <span><%= alert %></span>
  </div>
<% end %>
<% if notice = flash[:notice] %>
<div role="alert" class="alert alert-success alert-soft">
  <span><%= notice %></span>
</div>
<% end %>

app/views/admin/shared/_drawer.html.erb
<div class="drawer drawer-end">
  <input id="<%= drawer_id %>" type="checkbox" class="drawer-toggle" />
  <div class="drawer-content">
    <!-- Page content here -->
    <label for="<%= drawer_id %>" class="drawer-button btn btn-xs btn-primary"><%= button_name || "操作" %></label>
  </div>
  <div class="drawer-side">
    <label for="<%= drawer_id %>" aria-label="close sidebar" class="drawer-overlay"></label>
    <div class="bg-base-200 min-h-full w-180 p-18">
      <%= render drawer_content, item: item %>
    </div>
  </div>
</div>

app/views/admin/shared/_filter.html.erb
<div class="card card-border border-base-300 card-sm">
  <div class="card-body gap-4">
    <%= render "admin/students/filter_form" %>
  </div>
</div>

app/views/admin/shared/_footer.html.erb
<footer class="sticky bottom-0 z-50 footer sm:footer-horizontal footer-center bg-base-300 text-base-content p-4">
  <aside>
    <p>Copyright © <%= Date.current.year %> - 新梦想教育</p>
  </aside>
</footer>

app/views/admin/shared/_navbar.html.erb
<div class="sticky top-0 z-50 navbar bg-primary text-primary-content shadow-md">
  <div class="container mx-auto flex items-center justify-between">
    <div class="flex items-center px-4">
      <div>
        <%= link_to "维拓校务管理平台", root_path, class: "text-xl font-bold transition-colors hover:text-primary-content/90" %>
        <div class="text-xs text-primary-content/70 mt-1">
          <% if authenticated? %>
            当前校区：<%= Thread.current[:campuse].name %> | 当前学期：<%= Thread.current[:semester].name %>
          <% end %>
        </div>
      </div>
    </div>
    
    <% if authenticated? %>
    <div class="hidden md:flex items-center flex-1 justify-center">
      <ul class="menu menu-horizontal px-1 space-x-1">
        <% if Current.user.has_role_by_campuse_id(Thread.current[:campuse].id, 'admin') %>
          <li>
            <%= link_to "用户管理", admin_users_path, class: "rounded-md hover:bg-primary-content/10 transition-colors" %>
          </li>
          <li>
            <%= link_to "学校管理", admin_schools_path, class: "rounded-md hover:bg-primary-content/10 transition-colors" %>
          </li>
          <li>
            <%= link_to "教师管理", admin_teachers_path, class: "rounded-md hover:bg-primary-content/10 transition-colors" %>
          </li>
        <% end %>
        <li class="relative">
          <details class="group">
            <summary class="rounded-md hover:bg-primary-content/10 transition-colors cursor-pointer">
              学员管理
            </summary>
            <ul class="absolute left-0 menu bg-base-100 rounded-lg z-50 w-52 p-2 shadow-lg border border-base-200 text-base-content transition-all duration-200">
              <li>
                <%= link_to "在班学员", admin_students_path(filter: "in_class"), class: "rounded-md hover:bg-base-100 transition-colors" %>
              </li>
              <li>
                <%= link_to "未入班学员", admin_students_path(filter: "not_in_class"), class: "rounded-md hover:bg-base-100 transition-colors" %>
              </li>
              <li>
                <%= link_to "有退课学员", admin_students_path(filter: "out_class"), class: "rounded-md hover:bg-base-100 transition-colors" %>
              </li>
            </ul>
          </details>
        </li>
        <li>
          <%= link_to "班级管理", admin_semester_klasses_path, class: "rounded-md hover:bg-primary-content/10 transition-colors" %>
        </li>
      </ul>
    </div>
    
    <div class="flex items-center px-4 gap-2">
      <ul class="menu menu-horizontal space-x-2 items-center">
        <li class="relative">
          <details class="group">
            <summary class="flex items-center gap-2 rounded-full hover:bg-primary-content/10 transition-colors cursor-pointer p-1">
              <span><%= Current.user.name %></span>
            </summary>
            <ul class="absolute right-0 menu bg-base-100 rounded-lg z-50 w-56 p-2 shadow-lg border border-base-200 text-base-content transition-all duration-200">
              <!--<li><%#= link_to "修改密码", edit_admin_user_path(Current.user) %></li>-->
              <li class="relative">
                <details class="group">
                  <summary class="cursor-pointer hover:bg-base-100 rounded-md">
                    校区切换
                  </summary>
                  <ul class="absolute right-0 menu bg-base-100 rounded-lg z-50 w-48 p-2 shadow-md border border-base-200 -mt-2">
                    <% Current.user.campuses.each do |campuse| %>
                      <li class="<%= "menu-active" if Thread.current[:campuse] == campuse %>">
                        <%= link_to campuse.name, switch_thread_campuse_admin_school_campuse_path(school_id: Thread.current[:campuse].school.id, id: campuse.id), data: { turbo_prefetch: false}, class: "rounded-md hover:bg-base-100 transition-colors" %>
                      </li>
                    <% end %>
                  </ul>
                </details>
              </li>
              <li class="relative">
                <details class="group">
                  <summary class="cursor-pointer hover:bg-base-100 rounded-md">
                    学期切换
                  </summary>
                  <ul class="absolute right-0 menu bg-base-100 rounded-lg z-50 w-48 p-2 shadow-md border border-base-200 -mt-2">
                    <% Thread.current[:campuse].school.semesters.each do |semester| %>
                      <li class="<%= "menu-active" if Thread.current[:semester] == semester %>">
                        <%= link_to semester.name, switch_thread_semester_admin_school_semester_path(school_id: Thread.current[:campuse].school.id, id: semester.id), data: { turbo_prefetch: false }, class: "rounded-md hover:bg-base-100 transition-colors" %>
                      </li>
                    <% end %>
                  </ul>
                </details>
              </li>
            </ul>
          </details>
        </li>
        <%= button_to "注销", session_path, method: :delete, class: "btn btn-sm btn-outline btn-primary-content/80 hover:bg-primary-content/10 transition-colors" if authenticated? %>

      </ul>
    </div>
    <% end %>
  </div>
</div>